"""add needs_review and raw_source_text to transactions

Revision ID: 42712a5ec9d0
Revises: 7417a8ec7556
Create Date: 2026-08-12 22:33:20.872233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '42712a5ec9d0'
down_revision: Union[str, Sequence[str], None] = '7417a8ec7556'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('needs_review', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('transactions', sa.Column('raw_source_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'raw_source_text')
    op.drop_column('transactions', 'needs_review')
    # ### end Alembic commands ###
