"""add dedupe_hash to transactions

Revision ID: 7417a8ec7556
Revises: 901f4615b9a9
Create Date: 2026-08-12 22:09:19.896621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7417a8ec7556'
down_revision: Union[str, Sequence[str], None] = '901f4615b9a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('dedupe_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_transactions_dedupe_hash'), 'transactions', ['dedupe_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_dedupe_hash'), table_name='transactions')
    op.drop_column('transactions', 'dedupe_hash')
    # ### end Alembic commands ###
